export type TerrainsType =
    | "desert"
    | "grasslands"
    | "mountains"
    | "jungle"
    | "rainforests"
    | "tundra"
    | "ice caves"
    | "mountain ranges"
    | "swamp"
    | "jungles"
    | "gas giant"
    | "forests"
    | "lakes"
    | "grassy hills"
    | "swamps"
    | "cityscape"
    | "ocean"
    | "rock"
    | "mountain"
    | "barren"
    | "scrublands"
    | "savanna"
    | "canyons"
    | "sinkholes"
    | "volcanoes"
    | "lava rivers"
    | "caves"
    | "rivers"
    | "airless asteroid"
    | "glaciers"
    | "ice canyons"
    | "fungus forests"
    | "fields"
    | "rock arches"
    | "grass"
    | "plains"
    | "urban"
    | "hills"
    | "oceans"
    | "bogs"
    | "savannas"
    | "rocky islands"
    | "seas"
    | "mesas"
    | "unknown"
    | "deserts"
    | "reefs"
    | "islands"
    | "rocky deserts"
    | "valleys"
    | "ash"
    | "toxic cloudsea"
    | "plateaus"
    | "verdant"
    | "rocky canyons"
    | "acid pools"
    | "rocky"
    | "vines"
    | "cities"
    | "savannahs"
    | "cliffs";

export type ClimateType =
    | "arid"
    | "temperate"
    | "tropical"
    | "frozen"
    | "murky"
    | "windy"
    | "hot"
    | "artificial temperate"
    | "frigid"
    | "humid"
    | "moist"
    | "polluted"
    | "unknown"
    | "superheated"
    | "subartic"
    | "artic"
    | "rocky";
